name: Drupal CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, ctype, iconv, json, tokenizer, mysql
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-progress
    
    # Add your testing scripts here
    - name: Run Tests
      run: echo "Run your Drupal tests here"
